# Generated by Django 5.2.3 on 2025-07-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria de Despesa',
                'verbose_name_plural': 'Categorias de Despesas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', help_text='Ex: django.core.mail.backends.smtp.EmailBackend (para SMTP) ou django.core.mail.backends.console.EmailBackend (para testes).', max_length=255, verbose_name='Backend de Email')),
                ('email_host', models.CharField(blank=True, help_text='Endereço do servidor SMTP (ex: smtp.gmail.com).', max_length=255, null=True, verbose_name='Host SMTP')),
                ('email_port', models.IntegerField(blank=True, default=587, help_text='Porta do servidor SMTP (ex: 587 para TLS, 465 para SSL).', null=True, verbose_name='Porta SMTP')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Marque para usar TLS (Transport Layer Security) para conexão segura.', verbose_name='Usar TLS?')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Marque para usar SSL (Secure Sockets Layer). Se TLS for True, SSL deve ser False.', verbose_name='Usar SSL?')),
                ('email_host_user', models.CharField(blank=True, help_text='Nome de usuário para autenticação SMTP (geralmente seu e-mail completo).', max_length=255, null=True, verbose_name='Usuário SMTP')),
                ('email_host_password', models.CharField(blank=True, help_text='Senha ou chave de API para autenticação SMTP. Nunca coloque sua senha principal aqui.', max_length=255, null=True, verbose_name='Senha SMTP / Chave API')),
                ('default_from_email', models.CharField(blank=True, help_text='Endereço de e-mail que aparecerá como remetente padrão (ex: noreply@seusistema.com).', max_length=255, null=True, verbose_name='Remetente Padrão')),
            ],
            options={
                'verbose_name': 'Configuração de Email',
                'verbose_name_plural': 'Configurações de Email',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Forma de Pagamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PoliticaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Política de Reembolso de Despesas V1.0', max_length=255, verbose_name='Nome da Política')),
                ('arquivo', models.FileField(upload_to='politicas_despesa/', verbose_name='Arquivo da Política (PDF)')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Política de Despesa',
                'verbose_name_plural': 'Políticas de Despesas',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo de Documento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo de Serviço')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Manutenção',
                'verbose_name_plural': 'Tipos de Manutenção',
                'ordering': ['nome'],
            },
        ),
    ]
