# Generated by Django 5.2.3 on 2025-07-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_categoriadespesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Política de Reembolso de Despesas V1.0', max_length=255, verbose_name='Nome da Política')),
                ('arquivo', models.FileField(upload_to='politicas_despesa/', verbose_name='Arquivo da Política (PDF)')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Política de Despesa',
                'verbose_name_plural': 'Políticas de Despesas',
                'ordering': ['-data_upload'],
            },
        ),
    ]
