"""
Django settings for meu_projeto_servico project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from django.contrib.messages import constants as messages
from pathlib import Path

import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Pega do ambiente ou usa default
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-7_c1ij_xocq_f-&%54m+q5zjx4*7xsy_ez%@)%(9x454#$=ds_')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG_VALUE', 'False') == 'True'


ALLOWED_HOSTS = []

# Configuração para Render
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
# ADICIONE ESTA LINHA TAMBÉM POR GARANTIA OU SE QUISER FIXO
ALLOWED_HOSTS.append('assistencia-tecnica-django.onrender.com')
# Se você quiser permitir todos os subdomínios .onrender.com (menos seguro para produção, mas útil para testes)
# ALLOWED_HOSTS.append('.onrender.com')


# Application definition
INSTALLED_APPS = [
    # Adicione esta linha AQUI, antes de 'django.contrib.staticfiles'
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'servico_campo',
    'servico_campo.templatetags',
    'configuracoes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Adicione Whitenoise Middleware AQUI, DEPOIS de SecurityMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'meu_projeto_servico.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'meu_projeto_servico.wsgi.application'

LOGIN_REDIRECT_URL = '/servico/dashboard/'  # Onde redirecionar após o login
LOGOUT_REDIRECT_URL = 'login'  # Onde redirecionar após o logout

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),  # Pega do Render
        conn_max_age=600  # Opcional: tempo de vida máximo da conexão
    )
}

# Fallback para SQLite em desenvolvimento local se DATABASE_URL não estiver definida
if os.environ.get('DATABASE_URL') is None:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_L10N = True
USE_TZ = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),  # Para traduções do projeto como um todo
    # Embora o comando makemessages encontre apps automaticamente,
    # ter esta linha aqui ainda é útil para compilemessages e para o Django saber onde procurar.
    # Mas não é estritamente necessário apontar para 'servico_campo/locale' aqui, pois o makemessages já o fará.
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# Onde `collectstatic` vai copiar todos os arquivos estáticos para produção
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Seus apps já têm pastas 'static', mas se você tiver estáticos globais na raiz do projeto:
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'), # Ex: meu_projeto_servico/static/
# ]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configuração de arquivos estáticos (CSS, JS, Imagens do seu app)
# STATIC_URL = 'static/' # Já deve estar lá

# Configuração de arquivos de mídia (uploads do usuário)
MEDIA_URL = '/media/'
# A pasta 'media' na raiz do seu projeto
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}
