# Generated by Django 5.2.3 on 2025-07-02 14:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social / Nome')),
                ('cnpj_cpf', models.CharField(help_text='Formato: XX.XXX.XXX/XXXX-XX ou XXX.XXX.XXX-XX', max_length=18, unique=True, verbose_name='CNPJ / CPF')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(help_text='Sigla do estado (ex: SP, MG)', max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(help_text='Formato: XXXXX-XXX', max_length=10, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('contato_principal', models.CharField(max_length=100, verbose_name='Contato Principal')),
                ('telefone_contato', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Contato')),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Contato')),
                ('usuarios_associados', models.ManyToManyField(blank=True, related_name='empresas_associadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuários com Acesso')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Equipamento')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Série')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada do Equipamento')),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização do Equipamento no Cliente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico_campo.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'unique_together': {('cliente', 'nome', 'modelo')},
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(help_text='Ex: OS-YYYYMMDD-XXX', max_length=50, unique=True, verbose_name='Número da OS')),
                ('titulo_servico', models.CharField(max_length=255, verbose_name='Título do Serviço')),
                ('descricao_problema', models.TextField(verbose_name='Descrição do Problema / Motivo da OS')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_previsao_conclusao', models.DateField(blank=True, null=True, verbose_name='Previsão de Conclusão')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('AGUARDANDO_PLANEJAMENTO', 'Aguardando Planejamento'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('PENDENTE_APROVACAO', 'Pendente de Aprovação')], default='AGUARDANDO_PLANEJAMENTO', max_length=25, verbose_name='Status da OS')),
                ('observacoes_gerais', models.TextField(blank=True, null=True, verbose_name='Observações Gerais')),
                ('assinatura_cliente_data', models.TextField(blank=True, null=True, verbose_name='Dados da Assinatura do Cliente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servico_campo.cliente', verbose_name='Cliente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servico_campo.equipamento', verbose_name='Equipamento')),
                ('tecnico_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico_atuais', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
                ('tipo_manutencao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracoes.tipomanutencao', verbose_name='Tipo de Manutenção')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Documento')),
                ('arquivo', models.FileField(upload_to='documentos_os/', verbose_name='Arquivo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Documento')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracoes.tipodocumento', verbose_name='Tipo de Documento')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='servico_campo.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Documento da OS',
                'verbose_name_plural': 'Documentos da OS',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_despesa', models.DateField(verbose_name='Data da Despesa')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor (R$)')),
                ('comprovante_anexo', models.FileField(blank=True, null=True, upload_to='comprovantes_despesas/', verbose_name='Comprovante (Imagem/PDF)')),
                ('local_despesa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local da Despesa (Estabelecimento)')),
                ('aprovada', models.BooleanField(default=False, verbose_name='Aprovada para Reembolso')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável pela Despesa')),
                ('tipo_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracoes.formapagamento', verbose_name='Forma de Pagamento')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='servico_campo.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data_despesa', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relatorio', models.CharField(choices=[('RDO', 'Registro Diário de Obra (RDO)'), ('FAT', 'Ficha de Assistência Técnica (FAT)')], max_length=10, verbose_name='Tipo de Relatório')),
                ('data_relatorio', models.DateField(verbose_name='Data do Relatório')),
                ('descricao_atividades', models.TextField(verbose_name='Descrição das Atividades Realizadas')),
                ('problemas_identificados', models.TextField(blank=True, null=True, verbose_name='Problemas Identificados')),
                ('solucoes_aplicadas', models.TextField(blank=True, null=True, verbose_name='Soluções Aplicadas / Recomendações')),
                ('material_utilizado', models.TextField(blank=True, null=True, verbose_name='Materiais/Peças Utilizadas')),
                ('horas_normais', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas Normais')),
                ('horas_extras_60', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas Extras (60%)')),
                ('horas_extras_100', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas Extras (100%)')),
                ('km_rodado', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='KM Rodado')),
                ('local_servico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local do Serviço (Endereço)')),
                ('observacoes_adicionais', models.TextField(blank=True, null=True, verbose_name='Observações Adicionais')),
                ('assinatura_executante_data', models.TextField(blank=True, null=True, verbose_name='Dados da Assinatura do Executante')),
                ('visto_cliente_imagem', models.ImageField(blank=True, null=True, upload_to='vistos_clientes_relatorios/', verbose_name='Visto do Cliente')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação do Relatório')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_campo', to='servico_campo.ordemservico', verbose_name='Ordem de Serviço')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Executante')),
            ],
            options={
                'verbose_name': 'Relatório de Campo',
                'verbose_name_plural': 'Relatórios de Campo',
                'ordering': ['-data_relatorio', '-data_criacao'],
                'unique_together': {('ordem_servico', 'tipo_relatorio', 'data_relatorio', 'tecnico')},
            },
        ),
        migrations.CreateModel(
            name='FotoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_relatorios/', verbose_name='Foto')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição da Foto')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='servico_campo.relatoriocampo', verbose_name='Relatório de Campo')),
            ],
            options={
                'verbose_name': 'Foto do Relatório',
                'verbose_name_plural': 'Fotos do Relatório',
                'ordering': ['data_upload'],
            },
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome Completo do Membro')),
                ('funcao', models.CharField(help_text='Ex: Ajudante, Eletricista Auxiliar', max_length=100, verbose_name='Função na Equipe')),
                ('identificacao', models.CharField(blank=True, max_length=50, verbose_name='Identificação (Ex: RG, Matrícula)')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='servico_campo.ordemservico')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
                'unique_together': {('ordem_servico', 'nome_completo')},
            },
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Registro')),
                ('hora_entrada', models.TimeField(verbose_name='Hora de Entrada')),
                ('hora_saida', models.TimeField(blank=True, null=True, verbose_name='Hora de Saída')),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização (GPS ou Descrição)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Ponto')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to='servico_campo.ordemservico', verbose_name='Ordem de Serviço')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-data', '-hora_entrada'],
                'unique_together': {('tecnico', 'ordem_servico', 'data', 'hora_entrada')},
            },
        ),
    ]
