# Generated by Django 5.2.3 on 2025-07-04 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membroequipe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='membroequipe',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema'),
        ),
        migrations.AlterField(
            model_name='membroequipe',
            name='nome_completo',
            field=models.CharField(blank=True, help_text='Preencher apenas se não for um Usuário do Sistema', max_length=150, verbose_name='Nome Completo do Membro'),
        ),
        migrations.AlterUniqueTogether(
            name='membroequipe',
            unique_together={('ordem_servico', 'usuario')},
        ),
    ]
