# Generated by Django 5.2.3 on 2025-07-22 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_titular_conta', models.CharField(blank=True, help_text='Formato: XXX.XXX.XXX-XX', max_length=14, null=True, verbose_name='CPF do Titular da Conta')),
                ('nome_titular_conta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo do Titular')),
                ('banco_codigo', models.CharField(blank=True, help_text='Ex: 237 para Bradesco, 341 para Itaú', max_length=5, null=True, verbose_name='Código do Banco')),
                ('banco_nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Banco')),
                ('tipo_conta', models.CharField(blank=True, choices=[('CORRENTE', 'Conta Corrente'), ('POUPANCA', 'Conta Poupança')], max_length=10, null=True, verbose_name='Tipo de Conta')),
                ('agencia', models.CharField(blank=True, help_text='Com dígito, se houver', max_length=10, null=True, verbose_name='Número da Agência')),
                ('numero_conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da Conta')),
                ('digito_conta', models.CharField(blank=True, help_text='Se aplicável', max_length=2, null=True, verbose_name='Dígito Verificador (Conta)')),
                ('chave_pix_tipo', models.CharField(blank=True, choices=[('CPF', 'CPF'), ('EMAIL', 'E-mail'), ('CELULAR', 'Celular'), ('ALEATORIA', 'Chave Aleatória'), ('NENHUMA', 'Nenhuma')], default='NENHUMA', max_length=10, null=True, verbose_name='Tipo de Chave PIX')),
                ('chave_pix_valor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor da Chave PIX')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
