# Generated by Django 5.2.3 on 2025-08-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0002_alter_relatoriocampo_assinatura_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriocampo',
            name='assinatura_cliente',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/'),
        ),
        migrations.AlterField(
            model_name='relatoriocampo',
            name='assinatura_executante',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/'),
        ),
    ]
