# Generated by Django 5.2.3 on 2025-07-04 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0002_alter_membroequipe_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membroequipe',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='membroequipe',
            name='identificacao',
        ),
        migrations.RemoveField(
            model_name='membroequipe',
            name='nome_completo',
        ),
        migrations.AlterField(
            model_name='membroequipe',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Membro da Equipe (Usuário)'),
            preserve_default=False,
        ),
    ]
