# Generated by Django 5.2.3 on 2025-08-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0003_alter_relatoriocampo_assinatura_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='assinatura_cliente_conclusao',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/conclusao/', verbose_name='Assinatura do Cliente (Conclusão)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='assinatura_executante_conclusao',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/conclusao/', verbose_name='Assinatura do Executante (Conclusão)'),
        ),
    ]
