# Generated by Django 5.2.3 on 2025-07-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0003_remove_membroequipe_funcao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroequipe',
            name='funcao',
            field=models.CharField(blank=True, help_text='Ex: Ajudante, Eletricista Auxiliar', max_length=100, null=True, verbose_name='Função na Equipe'),
        ),
    ]
