# Generated by Django 5.2.3 on 2025-09-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0004_ordemservico_assinatura_cliente_conclusao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='motivo_reprovacao',
            field=models.TextField(blank=True, help_text='Detalhes sobre o porquê da ordem de serviço ter sido reprovada.', null=True, verbose_name='Motivo da Reprovação'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('PLANEJADA', 'Planejada'), ('AGUARDANDO_PLANEJAMENTO', 'Aguardando Planejamento'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('PENDENTE_APROVACAO', 'Pendente de Aprovação'), ('REPROVADA', 'Reprovada')], default='AGUARDANDO_PLANEJAMENTO', max_length=25, verbose_name='Status da OS'),
        ),
    ]
