# Generated by Django 5.2.3 on 2025-07-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0004_membroequipe_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='localizacao_saida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização de Saída (GPS ou Descrição)'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='localizacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização de Entrada (GPS ou Descrição)'),
        ),
    ]
