# Generated by Django 5.2.3 on 2025-07-04 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0005_registroponto_localizacao_saida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraJornadaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Regra')),
                ('horas_normais_diarias', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Horas Normais Diárias (Ex: 8.00)')),
                ('inicio_jornada_normal', models.TimeField(default=datetime.time(8, 0), verbose_name='Início da Jornada Normal (HH:MM)')),
                ('fim_jornada_normal', models.TimeField(default=datetime.time(17, 0), verbose_name='Fim da Jornada Normal (HH:MM)')),
                ('inicio_extra_60', models.TimeField(default=datetime.time(17, 0, 1), verbose_name='Início da Hora Extra 60% (HH:MM)')),
                ('fim_extra_60', models.TimeField(default=datetime.time(22, 0), verbose_name='Fim da Hora Extra 60% (HH:MM)')),
                ('inicio_extra_100', models.TimeField(default=datetime.time(22, 0, 1), verbose_name='Início da Hora Extra 100% (HH:MM)')),
                ('considerar_sabado_100_extra', models.BooleanField(default=True, verbose_name='Considerar Sábado 100% Extra')),
                ('considerar_domingo_100_extra', models.BooleanField(default=True, verbose_name='Considerar Domingo 100% Extra')),
                ('is_default', models.BooleanField(default=False, verbose_name='Regra Padrão (Default)')),
            ],
            options={
                'verbose_name': 'Regra de Jornada de Trabalho',
                'verbose_name_plural': 'Regras de Jornada de Trabalho',
            },
        ),
    ]
