# Generated by Django 5.2.3 on 2025-09-19 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0005_ordemservico_motivo_reprovacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAprovacaoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada')], max_length=10, verbose_name='Ação Realizada')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário/Motivo')),
                ('data_acao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Ação')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_aprovacoes', to='servico_campo.ordemservico', verbose_name='Ordem de Serviço')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Histórico de Aprovação da OS',
                'verbose_name_plural': 'Históricos de Aprovação da OS',
                'ordering': ['-data_acao'],
            },
        ),
    ]
