# Generated by Django 5.2.3 on 2025-07-04 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0006_regrajornadatrabalho'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria de Problema',
                'verbose_name_plural': 'Categorias de Problemas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SubcategoriaProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Subcategoria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='servico_campo.categoriaproblema', verbose_name='Categoria Principal')),
            ],
            options={
                'verbose_name': 'Subcategoria de Problema',
                'verbose_name_plural': 'Subcategorias de Problemas',
                'ordering': ['categoria__nome', 'nome'],
                'unique_together': {('categoria', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ProblemaRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Comentário / Observação do Problema')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servico_campo.categoriaproblema', verbose_name='Categoria do Problema')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemas_identificados_detalhes', to='servico_campo.relatoriocampo', verbose_name='Relatório de Campo')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servico_campo.subcategoriaproblema', verbose_name='Subcategoria do Problema')),
            ],
            options={
                'verbose_name': 'Problema Identificado',
                'verbose_name_plural': 'Problemas Identificados',
                'ordering': ['categoria__nome', 'subcategoria__nome'],
            },
        ),
    ]
