# Generated by Django 5.2.3 on 2025-09-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0006_historicoaprovacaoos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_aprovacao_gestor',
            field=models.DateTimeField(blank=True, help_text='Data em que o gestor aprovou e concluiu oficialmente a OS.', null=True, verbose_name='Data da Aprovação (Gestor)'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, help_text='Data em que o responsável finalizou o serviço em campo.', null=True, verbose_name='Data de Fechamento (Responsável)'),
        ),
    ]
