# Generated by Django 5.2.3 on 2025-07-08 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0007_categoriaproblema_subcategoriaproblema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriocampo',
            name='problemas_identificados',
        ),
    ]
