# Generated by Django 5.2.3 on 2025-09-19 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0007_ordemservico_data_aprovacao_gestor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoaprovacaoos',
            name='data_finalizacao_tecnico',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Finalização (Responsável)'),
        ),
        migrations.AddField(
            model_name='historicoaprovacaoos',
            name='tecnico_finalizou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_finalizadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável que Finalizou'),
        ),
        migrations.AlterField(
            model_name='historicoaprovacaoos',
            name='data_acao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Ação (Gestor)'),
        ),
        migrations.AlterField(
            model_name='historicoaprovacaoos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário da Ação (Gestor)'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, help_text='Data em que o técnico finalizou o serviço em campo.', null=True, verbose_name='Data de Fechamento (Responsável)'),
        ),
    ]
