# Generated by Django 5.2.3 on 2025-09-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0008_historicoaprovacaoos_data_finalizacao_tecnico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor efetivamente pago/reembolsado. Se deixado em branco, será usado o valor original da despesa.', max_digits=10, null=True, verbose_name='Valor Pago'),
        ),
    ]
