# Generated by Django 5.2.3 on 2025-07-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0008_remove_relatoriocampo_problemas_identificados'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_inicio_planejado',
            field=models.DateField(blank=True, help_text='Data planejada para o início das atividades da OS.', null=True, verbose_name='Início Planejado'),
        ),
    ]
