# Generated by Django 5.2.3 on 2025-09-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0009_contapagar_valor_pago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracaoEmail',
        ),
    ]
