# Generated by Django 5.2.3 on 2025-07-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0009_ordemservico_data_inicio_planejado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_inicio_real',
            field=models.DateTimeField(blank=True, help_text='Data e hora do primeiro registro de ponto ou início efetivo.', null=True, verbose_name='Início Real'),
        ),
    ]
