# Generated by Django 5.2.3 on 2025-07-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_categoriadespesa'),
        ('servico_campo', '0010_ordemservico_data_inicio_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='categoria_despesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuracoes.categoriadespesa', verbose_name='Categoria da Despesa'),
        ),
    ]
