# Generated by Django 5.2.3 on 2025-07-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0011_despesa_categoria_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='observacoes_entrada',
            field=models.TextField(blank=True, null=True, verbose_name='Observações de Entrada'),
        ),
    ]
