# Generated by Django 5.2.3 on 2025-09-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0011_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regrajornadatrabalho',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Tornar essa regra padrão'),
        ),
    ]
