# Generated by Django 5.2.3 on 2025-07-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0012_registroponto_observacoes_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='is_adiantamento',
            field=models.BooleanField(default=False, help_text='Marque se esta despesa for um adiantamento para o serviço, exigindo pagamento antes do início.', verbose_name='Adiantamento?'),
        ),
    ]
