# Generated by Django 5.2.3 on 2025-07-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_campo', '0013_despesa_is_adiantamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='aprovada',
        ),
        migrations.AddField(
            model_name='despesa',
            name='comentario_aprovacao',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário de Aprovação/Rejeição'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='status_aprovacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=10, verbose_name='Status de Aprovação'),
        ),
    ]
