# Generated by Django 5.2.3 on 2025-07-11 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_categoriadespesa'),
        ('servico_campo', '0014_remove_despesa_aprovada_despesa_comentario_aprovacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='paga',
            field=models.BooleanField(default=False, verbose_name='Paga?'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='categoria_despesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracoes.categoriadespesa', verbose_name='Categoria da Despesa'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='is_adiantamento',
            field=models.BooleanField(default=False, help_text='Marque se esta despesa for um adiantamento para o serviço, exigindo pagamento antes do início.', verbose_name='É Adiantamento?'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracoes.formapagamento', verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pagamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status do Pagamento')),
                ('comentario', models.TextField(blank=True, help_text='Adicione detalhes sobre o pagamento ou análise.', null=True, verbose_name='Comentário do Pagamento')),
                ('comprovante_pagamento', models.FileField(blank=True, null=True, upload_to='comprovantes_pagamento/', verbose_name='Comprovante de Pagamento (Imagem/PDF)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('despesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_a_pagar', to='servico_campo.despesa', verbose_name='Despesa Associada')),
                ('responsavel_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Pagamento')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
